### ISSUE TITLE
Yosys-compatible verilog

### ISSUE THREAD

**Issue by TheZoq2** [fischermoseley/manta#14]
This seems like a really cool project which I'm excited to use, but unfortunately, it doesn't seem to work very well with yosys, at least targeting ECP5s.

First, there are some compilation errors in the block_memory module

The type casts here aren't supported
```verilog
    localparam N_BRAMS = int'($ceil(real'(WIDTH) / 16.0));
```
and neither are these multi-dim arrays.
```verilog
    reg [N_BRAMS-1:0][ADDR_WIDTH-1:0] addra = 0;
    reg [N_BRAMS-1:0][15:0] dina = 0;
```
There may be others, but I looked to other methods at this point, in particular running through https://github.com/zachjs/sv2v takes care of most of these, but the `real` cast is still a problem.

With sv2v and some manual intervention in the `N_BRAMS` computation I was able to get it to compile, but yosys seems to fail to map the BRAM to BRAMs. I can't see an obvious reason for that :/

Edit: The config I used
```yaml
---
cores:
  my_logic_analyzer:
    type: logic_analyzer
    sample_depth: 4096
    trigger_loc: 1000

    probes:
      lp_detect: 1
      dbg_raw_ddr: 2
      dbg_raw_deser: 16
      dbg_aligned: 16
      dbg_aligned_valid: 2
      dbg_wait_sync: 2

    triggers:
      - moe FALLING

uart:
  port: "auto"
  baudrate: 115200
  clock_freq: 100000000
```
