### ISSUE TITLE
Add method for dumping logic analyzer contents to Python

### ISSUE THREAD

**Issue by fischermoseley** [fischermoseley/manta#5]
This isn't necessarily hard - but it's worth thinking about how signals should be formatted. For instance, if I've got a logic analyzer with a config of: 

```yaml
---
cores:
  my_logic_analyzer:
    type: logic_analyzer
    sample_depth: 4096
    trigger_loc: 1000

    probes:
      probe0: 1
      probe1: 2

    triggers:
      - probe0 RISING
```

Then does it make sense to look at the capture data as:

```python
>>> data = my_logic_analyzer.capture()
>>> data.probe0
[sample_0, sample_1, sample_2...]
>>> data.trigger_location
1024
```

Or does another mechanism make sense?
